[project]
name = "manualcelllabeler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "codex>=1.8.22",
    "streamlit>=1.52.1",
]
